apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-manager
  template:
    metadata:
      labels:
        app: ad-manager
    spec:
      containers:
        - image: meshetr/ad-manager:v0.6-beta6
          name: ad-manager
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database
                  key: port
            - name: DB_SSL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: ssl
            - name: DB_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: database
                  key: timezone
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: name
            - name: GCP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-storage-client
                  key: credentials-json

---

apiVersion: v1
kind: Service
metadata:
  name: ad-manager-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: ad-manager
